{
  "openapi": "3.0.0",
  "info": {
    "title": "Textiles API",
    "description": "API con NodeJS y Express",
    "version": "1.0.0",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "servers": [
    {
      "url": ""
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "tags": [
    {
      "name": "Carts"
    },
    {
      "name": "Categories"
    },
    {
      "name": "Orders"
    },
    {
      "name": "Products"
    },
    {
      "name": "Users"
    }
  ],
  "paths": {
    "/cart": {
      "get": {
        "tags": [
          "Carts"
        ],
        "summary": "Return Carts by user token",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "post": {
        "tags": [
          "Carts"
        ],
        "summary": "Create Cart",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "userdId": "userId"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "201": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/cart/{itemId}": {
      "parameters": [
        {
          "name": "itemId",
          "in": "path",
          "description": "Unique identifier of the group.",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "put": {
        "tags": [
          "Carts"
        ],
        "summary": "Update Item by ID",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "productId": "productId",
                  "quantity": "quantity",
                  "size": "size",
                  "color": "color",
                  "user": {
                    "hola": "hola"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Carts"
        ],
        "summary": "Delete Item by ID",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/categories": {
      "get": {
        "tags": [
          "Categories"
        ],
        "summary": "Devolver",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "post": {
        "tags": [
          "Categories"
        ],
        "summary": "Crear carta",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "userdId": "userId"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/categories/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "Unique identifier of the group.",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "tags": [
          "Categories"
        ],
        "summary": "Devolver",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": [
          "Categories"
        ],
        "summary": "Update Category by ID",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "productId": "productId",
                  "quantity": "quantity",
                  "size": "size",
                  "color": "color",
                  "user": {
                    "hola": "hola"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Categories"
        ],
        "summary": "Delete categorie by ID",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/place-order": {
      "post": {
        "tags": [
          "Orders"
        ],
        "summary": "Place Order",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "userdId": "userId"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/categories/{id}/products": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "Unique identifier of the group.",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Devolver",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "post": {
        "tags": [
          "Products"
        ],
        "summary": "Place Order",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "userdId": "userId"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/categories/{catId}/products/{prodId}": {
      "parameters": [
        {
          "name": "catId",
          "in": "path",
          "description": "Unique identifier of the group.",
          "required": true,
          "schema": {
            "type": "string"
          }
        },
        {
          "name": "prodId",
          "in": "path",
          "description": "Unique identifier of the group.",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "tags": [
          "Products"
        ],
        "summary": "Devolver product by ID and category ID",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "put": {
        "tags": [
          "Products"
        ],
        "summary": "Update Category by ID",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "productId": "productId",
                  "quantity": "quantity",
                  "size": "size",
                  "color": "color",
                  "user": {
                    "hola": "hola"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Products"
        ],
        "summary": "Delete categorie by ID",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/mercado-pago-notifications": {
      "post": {
        "tags": [
          "Orders"
        ],
        "summary": "Notifications mercado pago test",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "userdId": "userId"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/validate-user": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Notifications mercado pago test",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "userdId": "userId"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/change-password": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Notifications mercado pago test",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "userdId": "userId"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Notifications mercado pago test",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "userdId": "userId"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/profile": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Devolver product by ID and category ID",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Return All Users",
        "responses": {
          "200": {
            "description": "Succesfull Response",
            "content": {
              "application/json": {}
            }
          }
        }
      },
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Create User",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "",
                  "lastname": "",
                  "email": "",
                  "password": "",
                  "nationality": ""
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Succesfull Response",
            "content": {
              "application/json": {}
            }
          }
        }
      }
    }
  }
}